name: CI

on: [push, pull_request]

jobs:
  jobA:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Print "Hello World!"
        run: echo "Hello World!"
  jobB:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Print "Hello World!"
        run: echo "Hello World!"
