name: CI

on: [push, pull_request]

jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Print "Hello World!"
        run: echo "Hello World!"

  second-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Print "Hello World!"
        run: echo "Hello World!"
