name: CI

on: [push, pull_request]

jobs:
  file-conventions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Print "Hello World!"
        run: echo "Hello World!"
